title: Elixir |> Asturias
description: Elixir Asturias users group.
baseurl: ""
url: ""
twitter_username: elixirasturias
github_username:  elixirasturias
author:
  name: dreamingechoes

# Build settings
markdown: kramdown
theme: tale
permalink: /:title
paginate: 5
plugins:
  - jekyll-feed
