title: Elixir |> Asturias
description: Elixir Asturias users group.
baseurl: ""
url: ""
twitter_username: elixirasturias
github_username:  elixirasturias
author:
  name: Elixir |> Asturias
  github: elixirasturias
  twitter: elixirasturias
  meetup: Elixir-Asturias

# Build settings
markdown: kramdown
remote_theme: chesterhow/tale
permalink: /:title
paginate: 5
plugins:
  - jekyll-paginate
  - jekyll-remote-theme
